NONE_SATELLITE_MODULE_NAME = "SatHost"
OSPF_SATELLITE_MODULE_NAME = "OspfSatellite"
LIPSIN_SATELLITE_MODULE_NAME = "LipsinSatellite"
PIM_SATELLITE_MODULE_NAME = "PimSatellite"
MULTILAYER_SATELLITES_PATH = "/home/zhf/Projects/OmnetppProjects/Multilayer-satellites/"
